name: Release Helm Charts
on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git user
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser job
        uses: helm/chart-releaser-action@v1.6.0
        with:
          config: cr-config.yaml
        env:
          CR_TOKEN: ${{ secrets.CHARTS_REPO_TOKEN }}
